all:
  googleoauth2:
    client_id:             XYZ
    client_secret:         XYZ
    hosted_domain:    ''
    allowed_domains:  []
    after_signin_url:   '@homepage'
    create_users:        false
